version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build templates
          command: npm run build
      - run:
          name: Deploy to S3
          command: npm run deploy

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy