name: Build and Deploy
run-name: ${{ github.actor }} is postin' the schedule
env:
  SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
  SPACES_REGION: ${{ secrets.SPACES_REGION }}
  SPACES_KEY: ${{ secrets.SPACES_KEY }}
  SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
  SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }}
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm run deploy
