name: Build and Deploy
run-name: ${{ github.actor }} is postin' the schedule
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  build_and_deploy:
    runs-on: node:18.12.0
    steps:
      - run: npm install
      - run: npm run build
      - run: npm run deploy
